WIP: Add documentation for Relayer create, read, and update operations (#105)
OpenZeppelin/defender-docs pull request #106
Opened 2022-04-05 20:12 UTC by mok0230

Add documentation for Relayer create, read, and update operations per: https://github.com/OpenZeppelin/defender-docs/issues/105

Related PRs:

* `defender`: https://github.com/OpenZeppelin/defender/pull/2530
* `defender-client`: https://github.com/OpenZeppelin/defender-client/pull/93

comments inline

2022-04-05 21:24 UTC, shahnami commented on docs/modules/ROOT/pages/admin-api-reference.adoc
> +include::partial$network.adoc[]
❤️

2022-04-05 21:26 UTC, shahnami approved these changes
LGTM

2022-04-07 06:46 UTC, ernestognw requested changes

2022-04-07 06:46 UTC, ernestognw commented on docs/modules/ROOT/pages/admin-api-reference.adoc
> +include::partial$network.adoc[]
❤️

2022-04-07 06:46 UTC, ernestognw commented on docs/modules/ROOT/pages/relay-api-reference.adoc
> +* `whitelistReceivers`: an array of all valid addresses with which this relayer can interact; the relayer can send transactions to any address if this policy is undefined or set to an empty array
Heads up that setting to an empty array means the relayer is basically paused and can't send txs to any account

```suggestion
* `whitelistReceivers`: an array of all valid addresses with which this relayer can interact; the relayer can send transactions to any address if this policy is undefined
```

2022-04-08 19:46 UTC, merged