Active Vulnerability Detection
OpenZeppelin/defender-docs pull request #357
Opened 2024-07-29 11:06 UTC by dylankilkenny

2024-07-30 10:41 UTC, zanbel requested changes
@dylankilkenny looks great! made some minor copy suggestions

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +==== Automatically Generate Report
I suggest being more descriptive in the title and using "Automatically Trigger Report for Pull Requests"

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/assets/images/code-assets.png
The "Auto Run" header doesn't align with the text below. I suggest using "Auto Trigger"

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +==== Vulnerability Detection
title "Active Vulnerability Detection and Notification"

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +Vulnerability Detection provides a robust security measure by automatically scanning your assets for new critical vulnerabilities as they are discovered. This setting is applicable to both GitHub rep
"Active Vulnerability Detection and Notification provides a robust security measure by automatically scanning your assets for new vulnerabilities. 
This setting is applicable to both GitHub repositories and smart contracts. To enable this feature for Github repositories assets, you must activate the setting and select a specific branch to be monitored."

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +* *Automated Scanning*: Leveraging Defender's advanced scanning capabilities, this feature detects vulnerabilities in smart contracts, whether they are disclosed or undisclosed. When our team becomes
Automated Scanning: Leveraging Defender's advanced smart contracts scanning capabilities, when our team becomes aware of a new vulnerability, whether disclosed or undisclosed, we promptly update our scanning algorithms to detect it. We then scan all assets configured to be monitored

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +* *Automated Alerts*: Upon detection of a vulnerability, automated email notifications are sent to account administrators, alerting them to the potential risk. The notifications include relevant info
Automated Notification: Once the automatic scanning is completed an automated system notification email will be sent to inform you whether the vulnerability was detected in your monitored assets. If detected, the notifications include relevant information tailored to the nature of the vulnerability.

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +* *Risk Mitigation*: To aid in addressing and mitigating detected vulnerabilities, notifications may include suggestions for risk mitigation, providing actionable steps for administrators to protect
Risk Mitigation: When detected, to aid in addressing and mitigating detected vulnerabilities, notifications may include suggestions for risk mitigation, providing actionable steps for administrators to protect their smart contracts and associated assets.

2024-07-30 10:41 UTC, zanbel commented on docs/modules/ROOT/pages/module/code.adoc
> +By enabling Vulnerability Detection, users benefit from continuous, automated scanning and timely notifications, empowering them to respond quickly to new threats and maintain the security of their s
By enabling Active Vulnerability Detection and Notification for your assets, you can benefit from continuous, automated scanning and timely notifications, empowering you to respond quickly to new threats and maintain the security of your smart contracts and GitHub repositories. This proactive approach ensures that you can stay ahead of potential vulnerabilities and safeguard your code effectively.

2024-10-07 11:01 UTC, shahnami approved these changes
LGTM!

2024-10-07 11:13 UTC, merged