Relayer Tutorial
OpenZeppelin/defender-docs pull request #365
Opened 2024-08-23 16:27 UTC by oz-khizer

Basic relayer tutorial that checks relayer information, send tx and verify the relayer status.

2024-08-28 08:04 UTC, d-carmo requested changes
Just found that typo initializing the client object. Other than that, looks good.

2024-08-28 08:04 UTC, d-carmo commented on docs/modules/ROOT/pages/tutorial/relayer.adoc
> +const client = new Defender(
missing a `{`?
```suggestion
const client = new Defender({
```

2024-08-28 17:44 UTC, oz-khizer commented
> Just found that typo initializing the client object. Other than that, looks good.

Thanks for the review and finding the issue @d-carmo

2024-08-28 19:15 UTC, pasevin commented
I would wait until Defender 2.27.0 release and update the screenshots after it's released ;)

2024-08-29 06:39 UTC, d-carmo commented
> I would wait until Defender 2.27.0 release and update the screenshots after it's released ;)

You are right @pasevin . The 2.27.0 release is expected to go live on Monday morning (GMT). In any case yo ucan always get screenshots from the staging environment.

2024-09-03 17:08 UTC, oz-khizer commented
@pasevin and @d-carmo I updated the screenshots and added API key expiration section as well.

2024-09-05 18:56 UTC, tirumerla commented on docs/modules/ROOT/pages/tutorial/relayer.adoc
> +ts-node storeObject.ts
I would add `node storeObject.js` as well if folks wants to use node directly instead of ts-node

2024-09-05 18:56 UTC, tirumerla commented on docs/modules/ROOT/pages/tutorial/relayer.adoc
> +ts-node storeObject.ts
same here

2024-09-05 18:57 UTC, tirumerla reviewed
Add a minor comment, thanks for your contribution

2024-09-06 07:03 UTC, d-carmo approved these changes
LGTM

2024-09-06 20:12 UTC, openzeppelin-estimates commented
@tirumerla pushed new changes based on your suggestion.

2024-09-06 20:19 UTC, tirumerla approved these changes
lgtm, @openzeppelin-estimates make sure all the commits are signed..otherwise the merge will be blocked

2024-09-09 16:57 UTC, merged